### ISSUE TITLE
API still available?

### ISSUE THREAD

**Issue by robagar** [TGOlson/surfline#1]
Hiya - are you still able to access the API?  I just get a 500 error for a simple taxonomy request, and their support site has a distinctly unfriendly "We currently don't provide a public API but if you are interested in business opportunities..." answer to the query (https://support.surfline.com/hc/en-us/articles/13883685219227-Surfline-forecast-API-)

**Comment by robagar** [comment]
Nvm, using stormglass.io instead

**Comment by TGOlson** [comment]
Oh interesting. If it's not too much trouble could you share the call you were trying to make? I just checked and the test calls I was making still seem to be working, but to be fair it is definitely a weird (and not exactly public) api, so I could definitely see there being edge cases I didn't know about.

**Comment by robagar** [comment]
Sure, it was just a try out request with
```
fetchTaxonomy({id:"Earth", maxDepth:0})
```
which resulted in a 500 response with
```
{"message":"Error encountered"}
```

**Comment by TGOlson** [comment]
Ah, I think I see the issue. The id of the earth taxonomy is `58f7ed51dadb30820bb38782`.

You can try: `fetchTaxonomy({id: '58f7ed51dadb30820bb38782'})`.

Or there is a helper function you can use as starting point: `fetchEarthTaxonomy`.

I'll also take a look and see why that error code is so unhelpful, I'm not sure if that's from surfline or the library : )

**Comment by TGOlson** [comment]
Looks like that's just the surfline error response, sadly : (

You can see the responses but going to the direct links:

Good: https://services.surfline.com/taxonomy?type=taxonomy&id=58f7ed51dadb30820bb38782&maxDepth=0
Error: https://services.surfline.com/taxonomy?type=taxonomy&id=foo&maxDepth=0
